pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials-id')
        SONARQUBE_SERVER = 'SonarQube' 
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/bachiriy/Sensorium'
            }
        }

//        stage('SonarLint Verification') {
//            withSonarQubeEnv(credentialsId: 'sonarqube-id', installationName: 'SonarQube') {
//                sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar'
//            }
    //        steps {
    //            withSonarQubeEnv('SonarQube') {
    //                withMaven(maven:'Maven 3.5') {
    //                    sh 'mvn clean package sonar:sonar'
    //                }
    //            }
    //        }
    //    }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKERHUB_CREDENTIALS_USR/sensorium .'
            }
        }

        stage('Push to DockerHub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh 'docker push $DOCKERHUB_CREDENTIALS_USR/sensorium'
            }
        }

        stage('Deploy and Monitor') {
            steps {
                sh 'docker run -d -p 8080:8080 $DOCKERHUB_CREDENTIALS_USR/sensorium'
                echo 'Monitoring with Spring Actuator is now accessible at http://localhost:8080/actuator'
            }
        }
    }
}
